Repository rvalitov/zabbix-php-fpm, pull requests merged in 2019-12, with the labels that each got.

#9 Pools detection fix for CentOS
  zabbix/zabbix_php_fpm_discovery.sh
Labels: bug

#13 Fix for issue #12
  README.md
  zabbix/zabbix_php_fpm_discovery.sh
  zabbix/zabbix_php_fpm_status.sh
Labels: bug, documentation, enhancement

#15 Support for Zabbix version 4.0
  README.md
  zabbix/zabbix_php_fpm_template_4.0.xml
  zabbix/zabbix_php_fpm_template_4.2.xml
Labels: bug, enhancement

#16 Feature ISPConfig patch
  README.md
  ispconfig/ispconfig.patch
Labels: documentation, enhancement
